/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diary;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Chirram
 */
public class Preferences extends javax.swing.JPanel {

    /**
     * Creates new form Preferences
     */
    Design design;
    JFrame frame;
    public Preferences(Design design) {
        initComponents();
        this.design=design;
        frame=new JFrame("Preferences");
        
        frame.setLayout(new BorderLayout());
        frame.setContentPane(this);
        frame.pack();
        //frame.setSize(560, 400);
        frame.setVisible(true);
    }
    public void updatePicture()
    {
        FileInputStream fin=null;
        try {
            String path="",name="";
            JFileChooser jc=new JFileChooser();
            int x=jc.showOpenDialog(null);
            jc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if(x==JFileChooser.APPROVE_OPTION)
            {
                File f=jc.getSelectedFile();
                path=f.getAbsolutePath();
                name=f.getName();
                System.out.println(path);
            }  // File dir=new File(getClass().getResource("/image/").getPath());
            fin = new FileInputStream(new File(path));
           
           // System.out.println(dir.getAbsolutePath());
            //FileOutputStream fout=new FileOutputStream(dir.getAbsolutePath()+File.separator+"1.jpg");
            FileOutputStream fout=new FileOutputStream(design.location+"1.jpg");
            //JOptionPane.showMessageDialog(null,"1.jpg" );
           // System.out.println(dir.getAbsolutePath()+File.separator);
            try {
                while((x=fin.read())!=-1)
                {
                    try {
                        fout.write(x);
                    } catch (IOException ex) {
                        //JOptionPane.showMessageDialog(null,design.ppath+"1.jpg write" );
                        System.out.println("Write Exception");
                    }
                    
                }//JOptionPane.showMessageDialog(null,design.ppath+"1.jpg" );
            } catch (IOException ex) {
                //JOptionPane.showMessageDialog(null,design.ppath+"1.jpg read" );
                System.out.println("READ Exception");
            }
            
           
        } catch (FileNotFoundException ex) {
            System.out.println("Image updation error.");
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        changeUsername = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        changePassword = new javax.swing.JButton();
        changePic = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 1));
        setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Re-enter Password :");
        jLabel1.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(1, 1, 1));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Change Password ");
        jLabel3.setOpaque(true);

        changeUsername.setText("Change");
        changeUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeUsernameMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(1, 1, 1));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Change Username ");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(1, 1, 1));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Enter new User Name :");
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(1, 1, 1));
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Enter new Password :");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(1, 1, 1));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Change Pic : ");
        jLabel7.setOpaque(true);

        changePassword.setText("Change");
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
        });

        changePic.setText("Browse & Change");
        changePic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePicMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(changePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(changePic, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    String test="";
    private void changeUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUsernameMouseClicked
        // TODO add your handling code here:
        test="";
        test=username.getText();
        if(!test.equals(""))
        {
            try {
                design.sql="update User set username='"+test+"' where username='"+design.username+"';";
               // System.out.println(test+" sdf "+design.username);
                design.stmt.executeUpdate(design.sql);
//                design.con.commit();
                design.username=test;
                design.jLabel2.setText("Welcome "+test);
                design.userName.setText("Username : "+test);
                //JOptionPane.showMessageDialog(this,"Successfully updated.");
                design.sql="select * from User;";
                design.rs=design.stmt.executeQuery(design.sql);
                while(design.rs.next())
                {
                    System.out.println(design.rs.getString("username"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Preferences.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            //JOptionPane.showMessageDialog(this,"Please enter proper username!!");
        }
        username.setText("");
        design.revalidate();
        design.repaint();
        
    }//GEN-LAST:event_changeUsernameMouseClicked

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        // TODO add your handling code here:
        test="";
        test=pass1.getText();
        if(test.equals(pass2.getText()) && !test.equals(""))
        {
            try {
                design.sql="update User set password='"+test+"' where password='"+design.password+"';";
                design.stmt.executeUpdate(design.sql);
//                design.con.commit();
                design.password=test;
                //JOptionPane.showMessageDialog(this,"Successfully updated.");
            } catch (SQLException ex) {
                System.out.println("Password updation error.");
                Logger.getLogger(Preferences.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            //JOptionPane.showMessageDialog(this,"Please enter proper Values!!");
        }
        pass1.setText("");
        pass2.setText("");
        design.revalidate();
        design.repaint();
    }//GEN-LAST:event_changePasswordMouseClicked

    private void changePicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePicMouseClicked
        // TODO add your handling code here:
        updatePicture();
        design.setICon();
        design.revalidate();
        design.repaint();
    }//GEN-LAST:event_changePicMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePassword;
    private javax.swing.JButton changePic;
    private javax.swing.JButton changeUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
